<?php 

// ICI VOUS ALLEZ RECEVOIR UN FORMULAIRE EN METHODE HTTP POST

// VÉRIFIER SI LE FORMULAIRE EST BIEN ENVOYÉ EN POST, SINON IL FAUDRA ECHO UNE ERREUR

// SI VOTRE FORMULAIRE EST BIEN EN METHODE HTTP POST, IL FAUDRA METTRE DANS UNE VARIABLE VOTRE MESSAGE ENVOYER
// ENSUITE, IL FAUDRA UTILISE LA FONCTION urlencode() POUR ENCODER VOTRE MESSAGE.

// ENSUITE, IL FAUDRA CONSTRUIRE L'URL DE REDIRECTION VERS GOOGLE AVEC LE MESSAGE EN PARAMÈTRE GET

// ENSUITE, IL FAUDRA REDIRIGER VERS L'URL AVEC LA FONCTION header() ET LA FONCTION exit() POUR ARRÊTER L'EXÉCUTION DU SCRIPT